#! /bin/sh

SAGE_STANDARD=http://www.sagemath.org/packages/standard
SPD_STANDARD=http://spdproject.googlecode.com/files

# SPD minimum:
wget -nc $SAGE_STANDARD/termcap-1.3.1.p0.spkg
wget -nc $SAGE_STANDARD/zlib-1.2.3.p4.spkg
wget -nc $SAGE_STANDARD/readline-5.2.p6.spkg
wget -nc $SAGE_STANDARD/python-2.5.2.p9.spkg
wget -nc $SAGE_STANDARD/ipython-0.9.1.spkg

# notebook:
wget -nc $SPD_STANDARD/pexpect-2.0.p3.spkg
wget -nc $SAGE_STANDARD/twisted-8.1.0.p2.spkg
wget -nc $SAGE_STANDARD/setuptools-0.6c9.spkg
wget -nc $SAGE_STANDARD/jinja-1.2.spkg
wget -nc $SAGE_STANDARD/libgpg_error-1.6.p0.spkg
wget -nc $SAGE_STANDARD/libgcrypt-1.4.3.p0.spkg
wget -nc $SAGE_STANDARD/gnutls-2.2.1.p1.spkg
wget -nc $SAGE_STANDARD/python_gnutls-1.1.4.p3.spkg
wget -nc $SAGE_STANDARD/jquery-1.2.6.p0.spkg
wget -nc $SAGE_STANDARD/jqueryui-1.6r807svn.p0.spkg
wget -nc $SAGE_STANDARD/jsmath-3.6b.p1.spkg
wget -nc $SAGE_STANDARD/tinyMCE-3.2.0.2.p0.spkg
wget -nc $SPD_STANDARD/spd_notebook-3.4.1-3.spkg

# numpy, scipy matplotlib and sympy

wget -nc $SAGE_STANDARD/fortran-20071120.p5.spkg
wget -nc $SAGE_STANDARD/lapack-20071123.p0.spkg
wget -nc $SAGE_STANDARD/blas-20070724.spkg
#wget -nc $SAGE_STANDARD/atlas-3.8.3.p0.spkg
wget -nc $SAGE_STANDARD/numpy-1.2.0.p0.spkg
wget -nc $SAGE_STANDARD/scipy-20071020-0.6.p4.spkg
wget -nc $SAGE_STANDARD/matplotlib-0.98.5.3rc0-svn6910.p3.spkg
wget -nc $SAGE_STANDARD/sympy-0.6.4.spkg
